### PR TITLE
Export dictionary results

### PR DESCRIPTION
**Pull request by alexcodreanu86**
Give access to the dictionary tree

### CODE REVIEW

**Comment by alculquicondor** [comment]
Could you clarify why is this needed?

I'd rather favor finishing up the mapping to proper classes.

**Comment by alculquicondor** [comment]
Also, it seems that you didn't set up you email properly when committed.

**Comment by alexcodreanu86** [comment]
When working with the Ruby wrapper of libpg_query, I found it really useful to be able to see the the raw result that was returned from the C library. This was exposed as a `tree` property on the result object.

```ruby
query = PgQuery.parse("SELECT 1")
query.tree
# =>
 [{"SelectStmt"=>
    {"targetList"=>
      [{"ResTarget"=>
        {"val"=>
          {"ColumnRef"=> {"fields"=>[{"A_Star"=>{}}], "location"=>7}},
         "location"=>7}
      }],
     "fromClause"=>
      [{"RangeVar"=>
        {"relname"=>"users",
         "inhOpt"=>2,
         "relpersistence"=>"p",
         "location"=>14}}]
```

Since this library does not return a `PgQuery`, but instead an array of statements, there was no place to expose this tree. Instead of introducing this concept, I thought it would be less invasive to offer an alternative method that simply returns the result from the C library.

**Comment by alexcodreanu86** [comment]
@alculquicondor is there any chance you could release a minor version with this change? We are trying to use this library as part of our project. It would be great to be able to install this library through pip (without referencing the git repo). 

P.S. Thanks for the great library. It's helping us a lot on our project.

**Comment by alculquicondor** [comment]
@alexcodreanu86 it's done. Feel free to open more pull requests :)

**Pull request merged**
