### PR TITLE
Use git submodule to manage libpg_query dependency

### PR DESCRIPTION
**Pull request by wangym5106**
Using a shell script to download libpg_query's source code is insecure and may cause problems when deploying.
It's better to use `git submodule` to manage the dependency.

### CODE REVIEW

**Comment by wangym5106** [comment]
Hi @alculquicondor , can you review this PR? Thanks

**Comment by alculquicondor** [comment]
LGTM.
@kevinzg any concerns?

**Comment by kevinzg** [comment]
No, looks good. I'll merge it.

**Comment by wangym5106** [comment]
@kevinzg Thanks for merging this!
Is there any plan to push a new version to PyPI so that the change will apply to the installation from PyPI?

**Comment by kevinzg** [comment]
@wangym5106 I have released the master branch to PyPI as version 1.0rc7.
I noticed that the package file went from 37kB to 1.3MB due to including the pg_query source. I think we should remove them from the manifest file.

**Comment by wangym5106** [comment]
Actually this is what this PR intended to. The old version will download libpg_query when setting up the library, which caused problems:
- The install can be broken by dependency. If libpg_query pushed a breaking change, any new install of psqlparse will fail, even for an old version.
- The library can't install in a restricted network environment.
The new version which package the libpg_query directly fixed these problems.

Also, the increased size package won't be a problem. It can reduce installation time (refers to CI) and  make installation more stable.

**Comment by kevinzg** [comment]
You are right, my bad. Thanks for your work!

**Pull request merged**
